### ISSUE TITLE
 Unable to load shared library 'libyara' or one of its dependencies

### ISSUE THREAD

**Issue by mvardin** [airbus-cert/dnYara#13]
Hi
Thanks for your nice lib
I try to use this lib for my solution but I got error
I build and make libyara.so in ubuntu and make a .net core 6 console app for testing
but I got this error

`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libyara' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibyara: cannot open shared object file: No such file or directory
   at dnYara.Interop.Methods.yr_initialize()
   at dnYara.YaraContext..ctor() in C:\temp\dnYara\dnYara\YaraContext.cs:line 14
   at YaraInteractive.Program.Main(String[] args) in C:\temp\dnYara\Samples\YaraInteractive\Program.cs:line 13
Aborted (core dumped)
`

Can you please help me to solve this issue?

**Comment by mvardin** [comment]
I solve this issue
the problem was version
I build the correct version and solved
